In [2]:
import pandas as pd

df = pd.read_csv("../data/Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
print(df.shape)
print(df.columns.tolist())
print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

(9994, 21)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
None
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
0

In [4]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df.columns.tolist()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'country',
 'city',
 'state',
 'postal_code',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit']

In [5]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["ship_date"] = pd.to_datetime(df["ship_date"], errors="coerce")

In [6]:
df = df.drop_duplicates()

In [7]:
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [8]:
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()
df["quarter"] = df["order_date"].dt.quarter

In [9]:
df["shipping_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [10]:
df["profit_margin"] = df["profit"] / df["sales"]
df["profit_margin"] = df["profit_margin"].replace([float("inf"), -float("inf")], 0)
df["profit_margin"] = df["profit_margin"].fillna(0)

In [11]:
df["is_loss"] = (df["profit"] < 0).astype(int)

In [12]:
def discount_band(x):
    if x == 0:
        return "No Discount"
    elif x <= 0.2:
        return "Low"
    elif x <= 0.5:
        return "Medium"
    else:
        return "High"

df["discount_band"] = df["discount"].apply(discount_band)

In [13]:
df.to_csv("../data/superstore_clean.csv", index=False)

In [14]:
import pandas as pd

df = pd.read_csv("../data/superstore_clean.csv", encoding="utf-8")
df.to_csv("../data/superstore_clean_utf8.csv", index=False, encoding="utf-8")

In [15]:
df.to_csv("../data/superstore_clean_utf8sig.csv", index=False, encoding="utf-8-sig")

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/superstore_clean.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,discount,profit,year,month,month_name,quarter,shipping_days,profit_margin,is_loss,discount_band
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,41.9136,2016,11,November,4,3,0.1600,0,No Discount
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,219.5820,2016,11,November,4,3,0.3000,0,No Discount
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,0.00,6.8714,2016,6,June,2,4,0.4700,0,No Discount
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.45,-383.0310,2015,10,October,4,7,-0.4000,1,Medium
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.20,2.5164,2015,10,October,4,7,0.1125,0,Low

In [3]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month

In [4]:
monthly_sales = df.groupby(["year", "month"])["sales"].sum().reset_index()

monthly_sales["date"] = pd.to_datetime(
    monthly_sales["year"].astype(str) + "-" +
    monthly_sales["month"].astype(str) + "-01"
)

monthly_sales = monthly_sales.sort_values("date").reset_index(drop=True)

monthly_sales = monthly_sales[["date", "sales"]]

monthly_sales.head()

        date      sales
0 2014-01-01  14236.895
1 2014-02-01   4519.892
2 2014-03-01  55691.009
3 2014-04-01  28295.345
4 2014-05-01  23648.287

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/superstore_clean.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,discount,profit,year,month,month_name,quarter,shipping_days,profit_margin,is_loss,discount_band
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,41.9136,2016,11,November,4,3,0.1600,0,No Discount
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,219.5820,2016,11,November,4,3,0.3000,0,No Discount
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,0.00,6.8714,2016,6,June,2,4,0.4700,0,No Discount
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.45,-383.0310,2015,10,October,4,7,-0.4000,1,Medium
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.20,2.5164,2015,10,October,4,7,0.1125,0,Low

In [7]:
df = pd.read_csv("/Users/htetwaiyanoo/Senior_Project/data/superstore_clean.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,discount,profit,year,month,month_name,quarter,shipping_days,profit_margin,is_loss,discount_band
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,41.9136,2016,11,November,4,3,0.1600,0,No Discount
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,0.00,219.5820,2016,11,November,4,3,0.3000,0,No Discount
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,0.00,6.8714,2016,6,June,2,4,0.4700,0,No Discount
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.45,-383.0310,2015,10,October,4,7,-0.4000,1,Medium
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,0.20,2.5164,2015,10,October,4,7,0.1125,0,Low

In [8]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month

In [9]:
monthly_sales = df.groupby(["year", "month"])["sales"].sum().reset_index()

monthly_sales["date"] = pd.to_datetime(
    monthly_sales["year"].astype(str) + "-" +
    monthly_sales["month"].astype(str) + "-01"
)

monthly_sales = monthly_sales.sort_values("date").reset_index(drop=True)

monthly_sales = monthly_sales[["date", "sales"]]

monthly_sales.head()

        date      sales
0 2014-01-01  14236.895
1 2014-02-01   4519.892
2 2014-03-01  55691.009
3 2014-04-01  28295.345
4 2014-05-01  23648.287

In [10]:
train = monthly_sales.iloc[:-6].copy()
test = monthly_sales.iloc[-6:].copy()

print("Train rows:", len(train))
print("Test rows:", len(test))
print(test)

Train rows: 42
Test rows: 6
         date        sales
42 2017-07-01   45264.4160
43 2017-08-01   63120.8880
44 2017-09-01   87866.6520
45 2017-10-01   77776.9232
46 2017-11-01  118447.8250
47 2017-12-01   83829.3188

In [11]:
from sklearn.linear_model import LinearRegression

train["time_index"] = range(len(train))
test["time_index"] = range(len(train), len(train) + len(test))

lr_model = LinearRegression()
lr_model.fit(train[["time_index"]], train["sales"])

test["lr_pred"] = lr_model.predict(test[["time_index"]])

test[["date", "sales", "lr_pred"]]

         date        sales       lr_pred
42 2017-07-01   45264.4160  55881.446016
43 2017-08-01   63120.8880  56464.088204
44 2017-09-01   87866.6520  57046.730391
45 2017-10-01   77776.9232  57629.372579
46 2017-11-01  118447.8250  58212.014767
47 2017-12-01   83829.3188  58794.656954

In [12]:
all_data = monthly_sales.copy()
all_data["ma3_pred"] = all_data["sales"].rolling(window=3).mean().shift(1)

test["ma3_pred"] = all_data.loc[test.index, "ma3_pred"].values

test[["date", "sales", "lr_pred", "ma3_pred"]]

         date        sales       lr_pred      ma3_pred
42 2017-07-01   45264.4160  55881.446016  44588.124000
43 2017-08-01   63120.8880  56464.088204  47502.417300
44 2017-09-01   87866.6520  57046.730391  53789.009900
45 2017-10-01   77776.9232  57629.372579  65417.318667
46 2017-11-01  118447.8250  58212.014767  76254.821067
47 2017-12-01   83829.3188  58794.656954  94697.133400

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

lr_mae = mean_absolute_error(test["sales"], test["lr_pred"])
lr_rmse = np.sqrt(mean_squared_error(test["sales"], test["lr_pred"]))

ma3_mae = mean_absolute_error(test["sales"], test["ma3_pred"])
ma3_rmse = np.sqrt(mean_squared_error(test["sales"], test["ma3_pred"]))

comparison = pd.DataFrame({
    "Model": ["Linear Regression", "3-Month Moving Average"],
    "MAE": [lr_mae, ma3_mae],
    "RMSE": [lr_rmse, ma3_rmse]
})

comparison

                    Model           MAE          RMSE
0       Linear Regression  25585.295687  31005.141515
1  3-Month Moving Average  19298.804644  24002.772369